name: Terraform CI
'on':
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: write
jobs:
  terraform-ci:
    name: Terraform
    runs-on: ubuntu-latest
    # environment:
    #   name: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.1
        with:
          terraform_version: 1.8.4
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
