name: Terraform CI
'on':
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: write
  security-events: write
jobs:
  terraform-ci:
    name: Terraform
    runs-on: ubuntu-latest
    # environment:
    #   name: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.1
        with:
          terraform_version: 1.8.4

      - name: Terraform Format and Validate
        id: fmtval
        run: |
             terrafrom init 
             terraform fmt -check && terraform validate


      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.51.1

      - name: Run TFLint
        run: |
              tflint --version
              tflint --init
              tflint -f compact
      - name: Run tfsec
        uses: aquasecurity/tfsec-sarif-action@v0.1.4
        with:
          sarif_file: tfsec.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: tfsec.sarif

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          soft_fail: true
          download_external_modules: true
          github_pat: ${{ secrets.GH_PAT }}
          # This will add both a CLI output to the console and create a results.sarif file
          output_format: cli,sarif
          output_file_path: console,checkov-results.sarif
        env:
          GITHUB_OVERRIDE_URL: true  # optional: this can be used to instruct the action to override the global GIT config to inject the PAT to the URL
      # - name: Upload SARIF file
      #   uses: github/codeql-action/upload-sarif@v2
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: checkov-results.sarif


      - name: Run Terrascan
        id: terrascan
        uses: tenable/terrascan-action@main
        with:
          iac_type: 'terraform'
          iac_version: 'v14'
          policy_type: 'gcp'
          only_warn: true
          #scm_token: ${{ secrets.ACCESS_TOKEN }}
          #verbose: true
          sarif_upload: true
          #non_recursive:
          iac_dir: .
          #policy_path:
          #skip_rules:
          #config_path:
          #find_vulnerabilities:
          #webhook_url:
          #webhook_token:
