name: local-terraform CI
'on':
  push:
    branches: ["release","main" ] 
  pull_request:
    branches: [ "release","main" ] 

jobs:
  tf-ci:
    name: terraform analysis
    permissions:
      contents: write
      security-events: write
      actions: read
    uses: jomcyg/gcp-github-devsecops-workflows/.github/worflows/tf-ci.yml@jmc-dev-ghworkflow
    secrets: inherit
