name: local-terraform CI
'on':
  push:
    branches: ["release","main" ] 
  pull_request:
    branches: [ "release","main" ] 
permissions:
  contents: write
  security-events: write
  actions: read
jobs:
  tf-ci:
    name: terraform analysis
    uses: jomcyg/gcp-github-devsecops-workflows/.github/worflows/tf-ci.yml@jmc-dev-ghworkflow
