name: Terraform CI
'on':
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: write
jobs:
  terraform-ci:
    name: Terraform
    runs-on: ubuntu-latest
    # environment:
    #   name: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Setup Terraform
      #   uses: hashicorp/setup-terraform@v3.1.1
      #   with:
      #     terraform_version: 1.8.4

      # - name: Terraform Format and Validate
      #   id: fmtval
      #   run: terraform fmt -check && terraform validate


      # - name: Setup TFLint
      #   uses: terraform-linters/setup-tflint@v4
      #   with:
      #     tflint_version: v0.51.1

      # - name: Run TFLint
      #   run: |
      #         tflint --version
      #         tflint --init
      #         tflint -f compact

      # - name: TFSec
      #   uses: aquasecurity/tfsec-action@v1.0.3
      #   with:
      #     soft_fail: true



      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          soft_fail: true
          download_external_modules: true
          github_pat: ${{ secrets.GH_PAT }}
        env:
          GITHUB_OVERRIDE_URL: true  # optional: this can be used to instruct the action to override the global GIT config to inject the PAT to the URL
        
        # Results are generated only on a success or failure
        # this is required since GitHub by default won't run the next step
        # when the previous one has failed. Security checks that do not pass will 'fail'.
        # An alternative is to add `continue-on-error: true` to the previous step
        # Or 'soft_fail: true' to checkov.
        if: success() || failure()
        with:
          sarif_file: results.sarif

      - name: Run Terrascan
        id: terrascan
        uses: tenable/terrascan-action@main
        with:
          iac_type: 'terraform'
          iac_version: 'v14'
          policy_type: 'google'
          only_warn: true
          #scm_token: ${{ secrets.ACCESS_TOKEN }}
          #verbose: true
          #sarif_upload: true
          #non_recursive:
          #iac_dir:
          #policy_path:
          #skip_rules:
          #config_path:
          #find_vulnerabilities:
          #webhook_url:
          #webhook_token:
