name: local-terraform CI
'on':
  push:
    branches: ["release","main" ] 
#   pull_request:
#     branches: [ "release","main" ] 
  workflow_dispatch:
jobs:
  tf-ci:
    name: tf-ci
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: write
      id-token: write
      packages: write
      actions: read
      pull-requests: read
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
    #   - name: 'Sentinel Format'
    #     uses: hashicorp/sentinel-github-actions@master
    #     with:
    #         stl_actions_version: 0.14.2
    #         stl_actions_subcommand: 'apply'
    #         stl_actions_working_dir: '.'
    #         stl_actions_comment: true
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.1
        with:
          terraform_version: 1.8.4
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        # Update the values with the output from the setup step
        with:
            workload_identity_provider: projects/203546026970/locations/global/workloadIdentityPools/github-jomcyg/providers/github
            service_account: sa-jomcyggithub-gcloudauth@jmc-devsecops.iam.gserviceaccount.com

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2' #@v2.1.0
        with:
          version: '>= 475.0.0'
      - name: Terraform init-plan-vet
        id: fmtval
        run: |
            pwd && ls
            gcloud version
            terraform init
            terraform plan -out=test.tfplan
            terraform show -json ./test.tfplan > ./tfplan.json
      - name: 'Upload tfplan'
        uses: actions/upload-artifact@v4
        with:
            name: tf-plan
            path: ./test.tfplan
            retention-days: 3
        
  tf-cd:
    name: tf-cd
    needs: tf-ci
    runs-on: ubuntu-latest
    steps:
      - name: Download tfplan
        uses: actions/download-artifact@v4
        with:
            name: tf-plan
      - name: Terraform Apply
        id: tf-apply
        run: |
            ls
            terraform apply --var-file=terraform.auto.tfvars --auto-approve ./test.tfplan


